# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Client-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Layout
  pod 'SnapKit'		# autolayout
  pod 'Then'		# syntax sugar

  # Pods for Network
  pod 'Alamofire'
end
